/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PlaybackState {
  playing: boolean
  currentTime: number
  duration: number
  volume: number
  speed: number
}
export declare function mediaInit(): boolean
export declare function mediaPlayPause(): boolean
export declare function mediaLoadVideo(filePath: string): boolean
export declare function mediaGetState(): PlaybackState
export declare function mediaSeek(position: number): boolean
export declare function helloFromRust(): string
export declare function getSystemInfo(): string
